### ISSUE TITLE
Pin locked wallet freezes chrome app

### ISSUE THREAD

**Issue by karim0028** [BitLox/chrome-app#3]
1) Open Chrome Desktop app on mac
2) click on first pin locked wallet
3) enter pin (first wallet loads fine)
4) click on the next pin locked wallet
5) enter pin on bitlox

the chrome app gets stuck at "Loading wallet".  I then have to unplug USB and turn bitlox on and off and start again to access the second pin locked wallet

Expected response: the app should be able to switch between wallets seemlessly without having to reboot bitlox.

http://www.screencast.com/t/XZtcECcE

i had to unplug to get back, it basically just freezes...

**Comment by BitLox** [comment]
This is a known issue, it has to do with the app first having to figure out what the last address in the chain is (which becomes the current receiving address) then sending the signal to the BitLox to calculate and display this address on the internal screen. We are working on a fix for this.
Workaround: Please wait until the app has finished syncing the BitLox display with the calculated current receiving address. Once it is finished doing this, you can smoothly open a different wallet.

**Comment by BitLox** [comment]
Tested and fixed. Does not freeze when different wallet selected while first wallet is loading. 
Bitlox version 1.1.11, chrome Version 80.0.3983.2 (Official Build) dev (64-bit)
